version: '3.8'

services:
  sanarlav:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sanarlav_php
    volumes:
      - .:/var/www/symfony
    depends_on:
      - db
    networks:
      - symfony
    command: sh -c "composer install && php bin/console doctrine:migrations:migrate --no-interaction && php-fpm"

  nginx:
    image: nginx:latest
    container_name: sanarlav_nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/symfony
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - sanarlav
    networks:
      - symfony

  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    container_name: sanarlav_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: sanarlav_db
      MYSQL_USER: projet
      MYSQL_PASSWORD: laverie
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - symfony

networks:
  symfony:

volumes:
  mysql_data: